#!/bin/bash

# GitReport Git报表
# author: ektx <530675800@qq.com>


git log --pretty=tformat: --numstat | awk '
function add(s) {
	printf "\033[1;33m Add:\033[0m %5s", s
}
function del(s, f) {
	printf "\033[1;31m Del:\033[0m %5s   %s\n", s, f
}
function sum(a, d) {
	printf "\033[1;35m Add: %5s DEL: %5s\033[0m\n", a, d
}

{
	ADD+= $1; DEL+= $2;
	add($1) del($2, $3)
} END {
	sum(ADD, DEL)
}'