#!/bin/bash

# 输出格式
show(){
	local x=$1
	local y=$2
	local txt="$3"
	tput cup $x $y
	echo "$txt"
}
while [ : ]
do 
	clear
	now="$(date +"%r")"
	show 10 10 "MAIN MENU FOR $HOSTNAME - $now"
	show 11 10 "1. System Info"
	show 12 10 "2. Apache server stats"
	show 13 10 "3. MySQL Server stats"
	show 14 10 "4. FireWall stats"
	show 15 10 "5. Exit"
	tput cup 16 10; read -t 2 -p "Choice [1-5] ? " usrch
	# 对应模式
	case $usrch in
		1) read -t 2 -p "Showing system info, wait..." fakeinput;;
		2) read -t 2 -p "Showing Apache info, wait..." fakeinput;;
		3) read -t 2 -p "Showing MySQL info, wait..." fakeinput;;
		4) read -t 2 -p "Showing FireWall info, wait..." fakeinput;;
		5) echo "Bye."; exit 0;;
	esac
done
